import { useState, useEffect } from "react";
import Head from "next/head";
// import styles from "@/styles/Home.module.css";
import styles from "@/styles/styles.module.scss";
import Header from "@/components/Header";
import Timeline from "@/components/Timeline";
import Post from "@/components/Post";
import { mockData } from "@/mock/data";
import { InsertEmoticon } from "@mui/icons-material";
import { useRouter } from "next/navigation";
import apiClient from "@/lib/apiClient";

export default function Home() {
  // バックエンドから取得したデータを保持する
  const [posts, setPosts] = useState([]);
  // 画面遷移で使用するもの
  const router = useRouter();

  // ログインチェックのためにuseEffect
  useEffect(() => {
    // const token = localStorage.getItem("token");
    // if (!token) {
    //   router.push("/login");
    //   return;
    // }

    // 取得処理
    const fetchPosts = async () => {
      try {
        const response = await apiClient.get("/api/posts");
        console.log(response, "response取得チェック");
        setPosts(response.data);
      } catch (error) {
        console.log("投稿に失敗しました:", error);
      }
    };

    fetchPosts();

  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <Header />
        <Timeline />

        <div>
          {mockData &&
            mockData.map((item, index) => (
              <Post
                key={index}
                name={item.name}
                data={item.date}
                content={item.content}
                link={item.link}
              />
            ))}
        </div>
      </main>
    </>
  );
}
